# 2025 NVIDIA CORPORATION & AFFILIATES
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nic-configuration-operator-supported-nic-firmware
  namespace: {{ .RuntimeSpec.Namespace }}
data:
  Nvidia_mlx5_ConnectX-4_Lx-25.01: "1013 25.01-0.6.0 14.32.1900"
  Nvidia_mlx5_ConnectX-5-25.01: "1017 25.01-0.6.0 16.35.4030"
  Nvidia_mlx5_ConnectX-5_Ex-25.01: "1019 25.01-0.6.0 16.35.4030"
  Nvidia_mlx5_ConnectX-6-25.01: "101b 25.01-0.6.0 20.43.2026"
  Nvidia_mlx5_ConnectX-6_Dx-25.01: "101d 25.01-0.6.0 22.44.1036"
  Nvidia_mlx5_ConnectX-6_Lx-25.01: "101f 25.01-0.6.0 26.44.1036"
  Nvidia_mlx5_ConnectX-7-25.01: "1021 25.01-0.6.0 28.44.1036"
  Nvidia_mlx5_MT42822_BlueField-2_integrated_ConnectX-6_Dx-25.01: "a2d6 25.01-0.6.0 24.44.1036"
  Nvidia_mlx5_MT43244_BlueField-3_integrated_ConnectX-7_Dx-25.01: "a2dc 25.01-0.6.0 32.44.1036"
  Nvidia_mlx5_ConnectX-4_Lx-25.04: "1013 25.04-0.6.1 14.32.1900"
  Nvidia_mlx5_ConnectX-5-25.04: "1017 25.04-0.6.1 16.35.4030"
  Nvidia_mlx5_ConnectX-5_Ex-25.04: "1019 25.04-0.6.1 16.35.4030"
  Nvidia_mlx5_ConnectX-6-25.04: "101b 25.04-0.6.1 20.43.2566"
  Nvidia_mlx5_ConnectX-6_Dx-25.04: "101d 25.04-0.6.1 22.45.1016"
  Nvidia_mlx5_ConnectX-6_Lx-25.04: "101f 25.04-0.6.1 26.45.1016"
  Nvidia_mlx5_ConnectX-7-25.04: "1021 25.04-0.6.1 28.45.1016"
  Nvidia_mlx5_ConnectX-8-25.04: "1023 25.04-0.6.1 40.45.1016"
  Nvidia_mlx5_MT42822_BlueField-2_integrated_ConnectX-6_Dx-25.04: "a2d6 25.04-0.6.1 24.45.1020"
  Nvidia_mlx5_MT43244_BlueField-3_integrated_ConnectX-7_Dx-25.04: "a2dc 25.04-0.6.1 32.45.1020"
  Nvidia_mlx5_ConnectX-4_Lx-25.07: "1013 25.07-0.9.7 14.32.1010"
  Nvidia_mlx5_ConnectX-5-25.07: "1017 25.07-0.9.7 16.35.4554"
  Nvidia_mlx5_ConnectX-5_Ex-25.07: "1019 25.07-0.9.7 16.35.4554"
  Nvidia_mlx5_ConnectX-6-25.07: "101b 25.07-0.9.7 20.43.3608"
  Nvidia_mlx5_ConnectX-6_Dx-25.07: "101d 25.07-0.9.7 22.46.1006"
  Nvidia_mlx5_ConnectX-6_Lx-25.07: "101f 25.07-0.9.7 26.46.1006"
  Nvidia_mlx5_ConnectX-7-25.07: "1021 25.07-0.9.7 28.46.1006"
  Nvidia_mlx5_ConnectX-8-25.07: "1023 25.07-0.9.7 40.46.1006"
  Nvidia_mlx5_MT42822_BlueField-2_integrated_ConnectX-6_Dx-25.07: "a2d6 25.07-0.9.7 24.46.1006"
  Nvidia_mlx5_MT43244_BlueField-3_integrated_ConnectX-7_Dx-25.07: "a2dc 25.07-0.9.7 32.46.1006"
  Nvidia_mlx5_ConnectX-4_Lx-25.10: "1013 25.10-1.2.8 14.32.1908"
  Nvidia_mlx5_ConnectX-5-25.10: "1017 25.10-1.2.8 16.35.8002"
  Nvidia_mlx5_ConnectX-5_Ex-25.10: "1019 25.10-1.2.8 16.35.8002"
  Nvidia_mlx5_ConnectX-6-25.10: "101b 25.10-1.2.8 20.43.8002"
  Nvidia_mlx5_ConnectX-6_Dx-25.10: "101d 25.10-1.2.8 22.47.1026"
  Nvidia_mlx5_ConnectX-6_Lx-25.10: "101f 25.10-1.2.8 26.47.1026"
  Nvidia_mlx5_ConnectX-7-25.10: "1021 25.10-1.2.8 28.47.1026"
  Nvidia_mlx5_ConnectX-8-25.10: "1023 25.10-1.2.8 40.47.1026"
  Nvidia_mlx5_MT42822_BlueField-2_integrated_ConnectX-6_Dx-25.10: "a2d6 25.10-1.2.8 24.47.1026"
  Nvidia_mlx5_MT43244_BlueField-3_integrated_ConnectX-7_Dx-25.10: "a2dc 25.10-1.2.8 32.47.1026"
