# Copyright 2020 NVIDIA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This example demonstrates the use of the 'global' configuration field.
# Global config allows you to set default repository, version, and imagePullSecrets
# for all components. Individual components can override these values by specifying
# their own repository, version, or imagePullSecrets.

apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: nic-cluster-policy
spec:
  # Global configuration applied to all components that don't specify their own values.
  global:
    repository: nvcr.io/nvstaging/mellanox
    version: network-operator-v26.1.0-beta.3
    imagePullSecrets:
      - my-registry-secret
  ofedDriver:
    image: doca-driver
    # Override global version for OFED driver (repository inherited from global)
    version: doca3.3.0-26.01-0.5.6.0-0
    upgradePolicy:
      autoUpgrade: true
      drain:
        deleteEmptyDir: true
        enable: true
        force: true
        timeoutSeconds: 300
      maxParallelUpgrades: 1
  rdmaSharedDevicePlugin:
    # Only image is required - repository and version inherited from global
    image: k8s-rdma-shared-dev-plugin
    config: |
      {
        "configList": [
          {
            "resourceName": "rdma_shared_device_a",
            "rdmaHcaMax": 63,
            "selectors": {
              "vendors": ["15b3"],
              "deviceIDs": ["101b"]
            }
          }
        ]
      }
  nvIpam:
    # Only image is required - repository and version inherited from global
    image: nvidia-k8s-ipam
    enableWebhook: false
  secondaryNetwork:
    cniPlugins:
      # Only image is required - repository and version inherited from global
      image: plugins
    multus:
      # Only image is required - repository and version inherited from global
      image: multus-cni
