language: go

go:
  - "1.15"

env:
  - IMAGE_NAME=mellanox/network-operator

before_script:
  - go get -u github.com/mattn/goveralls

script:
  - make scripts/check-manifests.sh
  - make lint
  - make test-coverage
    #  - goveralls -coverprofile=network-operator.cover -service=travis-ci
  - make image

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  # Push image to Dockerhub on merge to master
  - provider: script
    skip_cleanup: true
    script: bash scripts/docker-push.sh $IMAGE_NAME latest $TRAVIS_CPU_ARCH
    on:
      branch: master
  # Push image to Dockerhub on tag
  - provider: script
    skip_cleanup: true
    script: bash scripts/docker-push.sh $IMAGE_NAME $TRAVIS_TAG $TRAVIS_CPU_ARCH
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
