- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: OFED_INIT_CONTAINER_IMAGE
    value: "nvcr.io/nvidia/mellanox/network-operator-init-container@sha256:4d75f5a1159b34785d55c4273f87397075883f998cd1b51d0419fa4e441ebf8f"
