apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: hostdevicenetworks.mellanox.com
spec:
  group: mellanox.com
  names:
    kind: HostDeviceNetwork
    listKind: HostDeviceNetworkList
    plural: hostdevicenetworks
    singular: hostdevicenetwork
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.state
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HostDeviceNetwork is the Schema for the hostdevicenetworks API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: HostDeviceNetworkSpec defines the desired state of HostDeviceNetwork
            properties:
              ipam:
                description: IPAM configuration to be used for this network
                type: string
              networkNamespace:
                description: Namespace of the NetworkAttachmentDefinition custom resource
                type: string
              resourceName:
                description: Host device resource pool name
                type: string
            type: object
          status:
            description: HostDeviceNetworkStatus defines the observed state of HostDeviceNetwork
            properties:
              appliedStates:
                description: AppliedStates provide a finer view of the observed state
                items:
                  description: AppliedState defines a finer-grained view of the observed
                    state of NicClusterPolicy
                  properties:
                    name:
                      type: string
                    state:
                      description: Represents reconcile state of the system
                      enum:
                      - ready
                      - notReady
                      - ignore
                      - error
                      type: string
                  required:
                  - name
                  - state
                  type: object
                type: array
              hostDeviceNetworkAttachmentDef:
                description: Network attachment definition generated from HostDeviceNetworkSpec
                type: string
              reason:
                description: Informative string in case the observed state is error
                type: string
              state:
                description: Reflects the state of the HostDeviceNetwork
                enum:
                - notReady
                - ready
                - error
                type: string
            required:
            - state
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
