apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: ipoibnetworks.mellanox.com
spec:
  group: mellanox.com
  names:
    kind: IPoIBNetwork
    listKind: IPoIBNetworkList
    plural: ipoibnetworks
    singular: ipoibnetwork
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.state
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: IPoIBNetwork is the Schema for the ipoibnetworks API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: IPoIBNetworkSpec defines the desired state of IPoIBNetwork
            properties:
              ipam:
                description: IPAM configuration to be used for this network.
                type: string
              master:
                description: Name of the host interface to enslave. Defaults to default
                  route interface
                type: string
              networkNamespace:
                description: Namespace of the NetworkAttachmentDefinition custom resource
                type: string
            type: object
          status:
            description: IPoIBNetworkStatus defines the observed state of IPoIBNetwork
            properties:
              ipoibNetworkAttachmentDef:
                description: Network attachment definition generated from IPoIBNetworkSpec
                type: string
              reason:
                description: Informative string in case the observed state is error
                type: string
              state:
                description: Reflects the state of the IPoIBNetwork
                enum:
                - notReady
                - ready
                - error
                type: string
            required:
            - state
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
