apiVersion: v2
name: sriov-network-operator
version: 0.1.0
kubeVersion: '>= 1.16.0'
appVersion: 1.1.0
description: SR-IOV network operator configures and manages SR-IOV networks in the kubernetes cluster
type: application
keywords:
  - sriov
home: https://github.com/k8snetworkplumbingwg/sriov-network-operator
sources:
  - https://github.com/k8snetworkplumbingwg/sriov-network-operator
