# Copyright 2020 NVIDIA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: mofed-{{ .RuntimeSpec.OSName }}{{ .RuntimeSpec.OSVer }}
  name: mofed-{{ .RuntimeSpec.OSName }}{{ .RuntimeSpec.OSVer }}-ds
  namespace: {{ .RuntimeSpec.Namespace }}
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: mofed-{{ .RuntimeSpec.OSName }}{{ .RuntimeSpec.OSVer }}
  template:
    metadata:
      # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
      # reserves resources for critical add-on pods so that they can be rescheduled after
      # a failure.  This annotation works in tandem with the toleration below.
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app: mofed-{{ .RuntimeSpec.OSName }}{{ .RuntimeSpec.OSVer }}
        driver-pod: mofed-{{ .CrSpec.Version }}
    spec:
      tolerations:
        # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
        # This, along with the annotation above marks this pod as a critical add-on.
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
{{if eq .RuntimeSpec.OSName "rhcos"}}
      serviceAccountName: ofed-driver
{{end}}
      hostNetwork: true
      {{- if .CrSpec.ImagePullSecrets }}
      imagePullSecrets:
      {{- range .CrSpec.ImagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - image: {{ .CrSpec.Repository }}/{{ .CrSpec.Image }}-{{ .CrSpec.Version }}:{{ .RuntimeSpec.OSName }}{{ .RuntimeSpec.OSVer }}-{{ .RuntimeSpec.CPUArch }}
          imagePullPolicy: IfNotPresent
          name: mofed-container
          securityContext:
            privileged: true
            seLinuxOptions:
              level: "s0"
          env:
            - name: HTTP_PROXY
              value: {{ .RuntimeSpec.HTTPProxy }}
            - name: HTTPS_PROXY
              value: {{ .RuntimeSpec.HTTPSProxy }}
            - name: NO_PROXY
              value: {{ .RuntimeSpec.NoProxy }}
          volumeMounts:
            - name: run-mlnx-ofed
              mountPath: /run/mellanox/drivers
              mountPropagation: Bidirectional
            - name: etc-network
              mountPath: /etc/network
            - name: host-etc
              mountPath: /host/etc
            - name: host-usr
              mountPath: /host/usr

            - name: host-udev
              mountPath: /host/lib/udev
          startupProbe:
            exec:
              command:
                [sh, -c, 'ls /.driver-ready']
            initialDelaySeconds: {{ .CrSpec.StartupProbe.InitialDelaySeconds }}
            failureThreshold: 60
            successThreshold: 1
            periodSeconds: {{ .CrSpec.StartupProbe.PeriodSeconds }}
          livenessProbe:
            exec:
              command:
                [sh, -c, 'lsmod | grep mlx5_core']
            initialDelaySeconds: {{ .CrSpec.LivenessProbe.InitialDelaySeconds }}
            failureThreshold: 1
            successThreshold: 1
            periodSeconds: {{ .CrSpec.LivenessProbe.PeriodSeconds }}
          readinessProbe:
            exec:
              command:
                [sh, -c, 'lsmod | grep mlx5_core']
            initialDelaySeconds: {{ .CrSpec.ReadinessProbe.InitialDelaySeconds }}
            failureThreshold: 1
            periodSeconds: {{ .CrSpec.ReadinessProbe.PeriodSeconds }}
      # unloading OFED modules can take more time than default terminationGracePeriod (30 sec)
      terminationGracePeriodSeconds: 120
      volumes:
        - name: run-mlnx-ofed
          hostPath:
            path: /run/mellanox/drivers
        - name: etc-network
          hostPath:
            path: /etc/network
        - name: host-etc
          hostPath:
            path: /etc
        - name: host-usr
          hostPath:
            path: /usr
        - name: host-udev
          hostPath:
            path: /lib/udev
      nodeSelector:
        feature.node.kubernetes.io/pci-15b3.present: "true"
        feature.node.kubernetes.io/system-os_release.ID: {{ .RuntimeSpec.OSName }}
        feature.node.kubernetes.io/system-os_release.VERSION_ID: "{{ .RuntimeSpec.OSVer }}"
      {{- if .NodeAffinity }}
      affinity:
        nodeAffinity:
          {{- .NodeAffinity | yaml | nindent 10 }}
      {{- end }}
